apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: a3Zib3dmaHk
  CLOUDINARY_KEY: NzQ2OTY1NzgyMzE1ODgy
  CLOUDINARY_SECRET: WDd1Ui1kUjlmUUJYRFJxb3JDeW5TV241R2pv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laM1YwYUhWc1lYWmhjM1VpTENKaElqb2lZMjExZUc0d05EaHRNR052YVRKNGN6RnFZM2h6TVdwdVlTSjkuX3Fhdm83ckU4ellOY0VDcUJBX1FPUQ
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAucXc5bW9mdS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA
